# Présentation article {- #presentation}


***

**Impact du non-emploi sur les revenus et la pauvreté : l'influence de l'hétérogénéité individuelle non-observable**  
*Pascale Breuil-Genier, Jean-Michel Hourriez, Stéfan Lollivier* (2004-5), Economie & prévision, 166:1-18.  

***

## Objet de recherche  
Variation de revenus qu'ont connu les ménages qui ont vécu une ou plusieurs transitions entre l'emploi et le non-emploi. PAS DE MODELISATION de revenus de ceux qui seraient restés en non-emploi pendant l'entièreté de la période d'observation; s'ils avaient accepté un emploi (i.e simulations).

Préciser la façon dont le non-emploi passé peut affecter les ressources présentes.

## Questions de recherche  
- Quel est l'impact du chômage ou de l'inactivité sur les revenus et la pauvreté ?  
- De combien varie le niveau de vie d'un ménage lorsque l'un de ses membres perd son emploi, ou au contraire reprend un emploi ?  
- L'augmentation ou la chute des revenus est-elle immédiate ou progressive ?  

Cette étude vise à décrire les variations de ressources engendrées par la transition emploi/non-emploi.  

## Données mobilisées  
*Données* : 4 premières vagues du panel européen des ménages (Insee & Eurostat), 1994 à 1997.  

*Champ* : ménage dont la PR est âgée de 17 à 60 ans, et n'est ni étudiante, ni militaire du contingent, ni retraitée (soit environ les deux tiers des ménages). Pour faciliter la prise en compte des caractéristiques de l'éventuel conjoint dans la modélisation économétrique (important car possible mutualisation des risques financiers limitant baisse de niveau de vie consécutive à perte d'emploi d'un des deux conjoints), l'étude est menée séparément sur les ménages formés :  

- autour d'un couple (12 392 observations correspondant à 3982 couples différents)  
- autour d'une personne seule (4725 observations correspondant à 1802 personnes différentes)  

*Variables*

|Variables expliquées|Variables explicatives|
|-|-|
|Logarithme du niveau de vie^[montant mensuel des revenus nets disponibles du ménage par équivalent adulte (revenus d'activités, revenus de remplacement, prestations).] |Âge (PR & conjoint)|
|Pauvreté|Sexe (PR seule)|
| |Diplôme (PR & conjoint)|
| |Nationalité (PR & conjoint)|
| |Nombre de personnes <14 ans|
| |Nombre de personnes >=14 ans|
| |Taille d'unité urbaine|
| |Situation par rapport à l'emploi $t$ et $t-1$ (PR & conjoint)|


Prise ou perte d'emploi non modélisées, SEULEMENT situation donnée modélisée (pas envie de modéliser décisions d'emploi en relation avec perspectives de gain financier attendues, mais plutôt mesurer les variations de revenu "effectives" liées aux changements de situations.)

Effet fixe : toutes les variables constantes au cours du temps seront "absorbées" par les effets individuels (i.e âge conjoint, sexe PR, diplôme, nationalité, et taille unité urbaine).

## Méthodologie  

1. Modèles de panel linéaire à *effet fixe* (effets non-emploi sur niveau de vie total du ménage) 

Modèle en coupe transversale estimé à l'aide des MCO (et sans effet fixe)  
$$(C)\;ln(ruc)_{it} = X'_{it}b + w_{it}$$
Les résultats du modèle à effet fixe sont comparés avec ceux d'une régression linéaire dans laquelle l'effet fixe est omis.  
Les estimateurs des paramètres $b$ par les MCO dans ce modèle (C) sont très différents de ceux estimés à partir du modèle (W) en *within*. En effet, dans (C), certaines variables explicatives sont endogènes (i.e. corrélées avec la perturbation $w_{it}$), ce qui biaise les estimateurs. Ainsi, l’effet du non-emploi sur les revenus estimés à partir de (C) reflète à la fois l’effet pur du non-emploi et l’effet de l’hétérogénéité individuelle inobservable : ceux qui sont sans emploi sont aussi ceux qui, par leurs caractéristiques, sont les plus susceptibles d’avoir de faibles revenus (faible employabilité…), d’où un effet non-emploi surestimé.

Modèle à effet fixe estimé en "within"
$$(W)\;ln(ruc)_{it} = X'_{it}b + a_i + u_{it}$$

- $ln(ruc)_{it}$ logarithme du revenu par UC du ménage $i$ à la date $t$,  
- $X_{it}$ vecteur des caractéristiques sociodemo du ménage (incluant à la fois les variables décrivant la trajectoire d'emploi et les variables permettant de contrôler *l'hétérogénéité individuelle observable*),  
- $a_i$ l'effet fixe (qui rend compte de *l'hétérogénéité individuelle non observable*),  
- $w_{it}$ et $u_{it}$ les perturbations (supposées de moyenne nulle, non corrélées aux vars explicatives et homoscédastiques).

Hypothèse importante du modèle (W): les variables explicatives sont supposées strictement exogènes. On admet que l'introduction d'un effet individuel est suffisante pour corriger des biais d'endogénéité entachant l'estimation du modèle (C).

+ corrélation des caractéristiques intrinsèques et inobservables avec la variable dynamique : variable joue alors rôle de *proxy* de l'hétérogénéité inobservable (donc coefficient pas correct).

***
Le modèle à *effet fixe* postule que toute l'hétérogénéité individuelle inobservable est résumée à travers un effet fixe individuel $a_i$ constant dans le temps, propre au ménage $i$. Ceci exclut que l'effet fixe varie dans le temps (forme du type $\alpha_i + \delta_it$, ou bien variation concomittante avec les variables explicatives $X_{it}$).  
Les variables explicatives sont supposées strictement endogènes.

***

2. Modèles *logit* à *effet fixe* (effets non-emploi sur pauvreté).  
$$ P(y_{it} = 1/x_{i1},...,x_{iT},c_i)=G(x_{it}\beta + c_i)$$  

- $y_{it}$ est la variable muette décrivant la pauvreté de l'individu $i$ à la date $t$,  
- $x_{i1},...,x_{iT}$ les variables explicatives à chacune des dates,   
- $c_i$ l'effet individuel et G la fonction : $G(z)=exp(z)/(1+exp(z))$.  
Je comprends pas la suite.  

*Résumé des modèles*  

a. modèles linéaires effets fixes (niveau de vie) + modèles logit effets fixes (pauvreté) pour les couples;  
b. modèles linéaires effets fixes + modèles logit effets fixes pour les personnes seules;  
c. modèle linéaire effet fixe influence sur le niveau de vie en fonction du niveau de diplôme (>bac / bac+) pour les couples;  
d. modèle linéaire effet fixe influence sur le niveau de vie en fonction de la génération (jeunes / intermédiaires / anciennes) pour les couples et les personnes seules.  

### Intérets de ces choix de méthodes  

Comparaison en coupe transversale des revenus des personnes avec ou sans emploi fournit une estimation biaisée de l'impact de la situation d'emploi sur le niveau de vie => caractéristiques inobservables des individus expliquent à la fois situation d'activité et revenu obtenu dans situation d'activité donnée (i.e corrélation des résidus des caracs inobservables avec la variable explicative ET la variable à expliquée). *Hétérogénéité inobservable*.

Hétérogénéité individuelle => données de panel. Permettent d'observer l'évolution du niveau de vie d'une même personne lorsqu'elle passe de l'emploi au non-emploi et vice-versa (i.e peut pas juste comparé revenus à date $t$ de personne 1 avec emploi et personne 2 sans-emploi sans considéré trajectoire de vie et caractéristiques individuelles inobservables qui influencent revenu en période d'emploi comme en période de non-emploi? e.g premières années en emploi, retour à l'emploi, non-emploi continu, non-emploi récurrent...)

Effet fixe = hétérogénéité individuelle non-observable v modèle linéaire de base dont hétérogénéité se retrouve dans résidu corrélé avec les variables explicatives (problème d'endogénéité). Estimateurs des variables explicatives dynamiques sont donc moins biaisés dans modèle à effet fixe, puisque effet fixe prend en compte variabilité individuelle (supposée constante dans le temps) en dehors de la perturbation $w_{it}$. Influence composition du ménage sur niveau de vie/pauvreté (i.e effets structurels).  

## Résultats  

À caractéristiques observables données, les ménages ont un niv de vie d'autant plus élevé (et sont d'autant moins pauvres) qu'ils habitent une uu de grande taille, effet particulièrement marqué en agglo parisienne. Âge effet significatif que pour personnes seules : niv vie augmente, pauvreté diminue. 

Surestimation des effets de la situation d'emploi présente ou passée sur niv de vie dans modèles sans effets fixes (car carac inobservables qui favorisent obtention d'un emploi influent aussi positivement sur le niveau de vie en période d'emploi ou non-emploi blablabla...).

Tenir compte des carac non-obs annule presque totalement l'écart de niv de vie courant entre ceux qui viennent de reprendre un emploi et ceux qui étaient déjà en emploi douze mois plus tôt. Hétérogénéité inobs contrôlée = coefficients des variables d'activité s'interprètent comme les effets propres de la perte ou de la reprise d'emploi. Dépendance d'état dans non-emploi $\rightarrow$ emploi < hétérogénéité : être s-e en $t-1$ n'affecterait pas, toutes choses égales par ailleurs, niv des ressources liées à l'emploi en $t$. Hausse niv de vie non-emploi $\rightarrow$ emploi ne paraîtrait pas plus importante au bout d'un an que dans l'immédiat.

Hausse (resp. baisse) niveau de vie liée à obtention (resp. perte) d'un emploi est plus élevée pour les personnes seules (de l'ordre de 30%) que pour les personnes en couple (de l'ordre de 20% s'il s'agit de la PR et un peu moins s'il s'agit du conjoint). Risques de variation du revenu mutualisés dans cas du couple.

## Conclusion  

1. Même une fois hétérogénéité individuelle inobservable prise en compte, subsiste écart fortement significatif, mais attendu, de niv de vie (ou risque pauv) entre personnes actuellement en emploi et personnes actuellement sans emploi.
2. Importance HII dans lies entre emploi et revenus : à âge, sexe, diplôme, nationalité et zone d'habitation identiques, les caracs permanentes et inobservables des individus jouent dans le même sens sur l'obtention d'un emploi et sur le niv de vie atteint en période d'emploi comme en période de non-emploi. De ce fait, l'écart constaté en coupe transversale entre niv de vie moyen d'une personne en emploi et niv de vie moyen de personne s-e s'explique pour moitié par des différences (obs ou non) entre les individus. Les caractéristiques sociodémo observables n'expliquent à elles seules qu'une faible partie de cet écart. 