# Modèles dynamiques {#mod-dyn}

Un modèle dynamique fait intervenir des retards sur une ou plusieurs variables (analyse du temps présent en fonction du temps présent ET du temps passé):

* si ces variables sont uniquement exogènes, on parlera de **modèles à retard échelonnés** comme dans la formule simple

$$y_t = c + \sum_{i=0}^r a_i x_{t-i} + \epsilon_t$$

  * $y_t$ valeur à la date $t$
  * $c$ point à l'origine (équivalent de $\beta_0$)
  * $a_i$ (équivalent de $\beta_i$): une unité de plus de $x_{t}$ sur $y_t$, en gardant $x_{t-1}$ constant.

Dans ce cas là, seule la valeur $x_{t-i}$ de la période passée impacte la valeur $y_t$ de la période présente. Cependant, ce modèle estimé par les MCO rencontre des problèmes de multicollinéarité (la variable $x_{t-1}$ est un multiple de la variable $x_{t-2}$, etc.), de degrée de liberté, et une tendance non-continuelle des coefficients estimés dans le temps (pas dans le même sens, pas la même ampleur).

* si les variables retardées correspondent à l'endogène (effet de.s variable.s explicatives s'étend sur plusieurs périodes $t$ d'une manière géométrique), on appellera ces modèles des **modèles autorégressifs**

$$y_t = c + \sum_{i=1}^r a_i x_{t-i} + \epsilon_t \\ou\\ y_t = c+\sum_{i=1}^r a_i y_{t-i}+bx_t + cz_t + \epsilon_t \\ (y_t = \alpha_0 + \beta_O x_t + \lambda y_{t-1} + u_t)$$
Ici, le présent ainsi que le passé impactent la période présente (par exemple, en EQ, notre avancement passé $y_{t-1}$, nos efforts présents $x_t$ ainsi que l'humeur du prof $z_t$ à la date $t$ impactent notre avancement présent $y_t$).

Si la période d'examen s'étend, on s'attend à ce que les coefficients $a_i$ diminuent, car la force du passé lointain sur le présent doit normalement moins se ressentir.

Dans le cas général, on parlera de modèles autorégressifs et à retards échelonnés (ou **modèle dynamique**):
$$y_t = c + \sum_{i=1}^r a_iy_{t-i} + \sum_{j=0}^l b_jx_{t-j} + \epsilon_t$$
à gauche : variables retardées endogènes.
à droite : retards échelonnés exogènes.

Nombreuses applications, en particulier lorsque l'on suppose l'existence d'une dépendance du phénomène observé par rapport à ses états antérieurs :

- étude du revenu disponible des ménages (dépend des dépenses passées et des revenus restants),
- étude des phénomènes de transmission de capitaux.

## Les modèles dynamiques autorégressifs
Exemple simple:
$$y_t = a + bx_t + cy_{t-1} + \epsilon_t$$

Question : les erreurs $\epsilon_t$ sont-elles corrélées ? $Cov(\epsilon_t,\epsilon_{t-1} \neq 0)$ ?

- si oui (i.e différent de 0)^[*Lagrange Multiplier (LM)* serial correlation test (voir Chapter 12 - *Time-series models* dans *Using Econometrics, A Practical Guide* de Studenmund)], problème car alors $y_t$ dépend non seulement de $\epsilon_t$ mais aussi de $\epsilon_{t-1},\epsilon_{t-2},\epsilon_{t-3}$, etc (corrélation des variables indépendantes avec perturbation + corrélation en série des perturbations => clashent avec MCO assumptions). 
- si non ($Cov(\epsilon_t,\epsilon_{t-1}= 0)$), alors les MCO sont utilisables.
  - mais suppose de **très gros échantillons** pour suffisamment de convergence des estimateurs.
  
Plusieurs tests possibles pour vérifier l'autocorrélation des résidus :

- **Test de Durbin-Watson** $\epsilon_t = \rho \epsilon_{t-1} + u_t$
  - $H_0$ : il y a non autocorrélation $\Leftrightarrow \rho=0$,
  - $H_1$ : il y a autocorrélation $\Leftrightarrow \rho \neq 0$ avec toujours $|\rho| < 1$.
  
Statistique de Durbin-Watson:
  $$H=\frac{\rho}{\sqrt{\frac{1}{n}-Var(a_1)}}$$
  
  * $\rho$ est l'estimateur de $\rho$, 
  * n la taille de l'échantillon et,
  * $Var(a_1)$ la variance estimée du premier retard sur l'endogène.
  
(problème avec les ^, vérifier les slides pour pas faire de bêtise)

## Méthode des moments généralisés (GMM)

Complément sur les [variables instrumentales](https://pyrrhamide.github.io/regressions/mod-id2.html#variables-instrumentales).

Dans toutes les stratégies d'estimation des modèles précédents, une hypothèse:

* les variables explicatives $x_{it}$ sont exogènes, i.e

$$E[\epsilon_{it}|\alpha_i,x_{i1},...x_{it}] = 0, \quad t=1,...T$$

* Que se passe-t-il si ce n'est pas le cas ? i.e. $E[\epsilon_{it}|x_{ijt}] \neq 0$ pour au moins un $j$.

Les MCO ne sont plus utilisables: **estimateurs biaisés**.

Méthode des momment généralisés (GMM) : méthodo d'estimation des différents modèles dynamiques. Généralise les MCO.

Idées des GMM:

* trouver $r$ variables (dites "instruments") $Z_i = \{z_i^1,...,z_i^r\}$ de moment nul $E[Z_i'\epsilon_i] = 0$.
* Comment les trouver ?
    * il peut s'agir de certaines variables explicatives $x_i$ dont on suppose l'exogénéité;
    * d'autres variables, parfois mêmes construites à partir des $x_i$.
* Avec ces instruments, l'estimateur GMM est calculé en fonction de ces conditions pour minimiser une forme quadratique^[Voir les slides pour l'équation, j'ai la flemme de la retranscrire ici.]

Exogénéité variables explicatives par rapport aux résidus fondamentale pour MCO (utile pour le within aussi?). Arrive souvent que cette hypothèse soit pas respectée. Variables endogènes; causalité inverse variable expliquée sur variables explicatives. MCO ne sont plus utilisables.

Plusieurs cas:

* r=K ou dim(r)=dim(X) : modèle "juste identifié". Autant d'instruments que de var explicatives, l'estimation se fait "simplement" en une étape.
* r>K ou dim(r)>dim(X) : modèle "sur-déterminé". Instruments > var explicatives. Il y a "trop" de variables, nécessité de procéder en 2 étapes:
    * **Etape 1** : équation d'instrumentation. Chaque régresseur **endogène** $X_j$ est régressé sur tous les instruments $Z$ et tous les régresseurs exogènes $X_j$. $x_j = Z \gamma_j + X_j \delta_j + \mu_j$. Les valeurs prédites $\hat x_j = Z \hat \gamma_j + X_j \hat \delta_j$ sont des instruments valides pour les $X_j$ endogènes.
    * **Etape 2** : $Y$ est régressé sur les valeurs prédites.